### ISSUE TITLE
How to use IndelEnsembler with multi samples

### ISSUE THREAD

**Issue by Keliang-Lyu** [kensung-lab/IndelEnsembler#1]
Hi,
I notice that TranSurVeyor and SurVIndel can only build workflow with single sample.
What can I do, if there are 100 samples in my project.
Regards!

**Comment by Mesh89** [comment]
IndelEnsembler runs on a single sample. You have to run it on each sample individually. After that, you can cluster the calls using the clustering utility we provide.

**Comment by Keliang-Lyu** [comment]
> IndelEnsembler runs on a single sample. You have to run it on each sample individually. After that, you can cluster the calls using the clustering utility we provide.

Thank you for the reply. 

The `build.sh` only build `compare-del` and `compare-ins`

Could I build the clustering utility by using follow command?
`g++ -std=c++11 -O2 ssw.c ssw_cpp.cpp clusterer.cpp -o clusterer`

**Comment by Mesh89** [comment]
Yes, that should build the clusterer.

**Comment by Keliang-Lyu** [comment]
> Yes, that should build the clusterer.

OK. thank you for your relpy
