### ISSUE TITLE
ValueError: Coordinates start=1049263 and end=1049262 imply a diffent length than sequence (length 0).

### ISSUE THREAD

**Issue by Keliang-Lyu** [kensung-lab/IndelEnsembler#2]
Hi,
When I running the `pipeline.sh`, I get the follow message.

```
Traceback (most recent call last):
  File "trans2ins.py", line 39, in <module>
    seq = str(fasta[src_chr][src_start:src_end])
  File "/share/home/biosoft/conda/envs/py27/lib/python2.7/site-packages/pyfaidx/__init__.py", line 699, in __getitem__
    return self._fa.get_seq(self.name, start + 1, stop)[::step]
  File "/share/home/biosoft/conda/envs/py27/lib/python2.7/site-packages/pyfaidx/__init__.py", line 121, in __getitem__
    raise ValueError("Coordinates start=%s and end=%s imply a diffent length than sequence (length %s)." % (self.start, self.end, len(self.seq)))
ValueError: Coordinates start=1049263 and end=1049262 imply a diffent length than sequence (length 0).
```

I find the records from TranSurVeyor result.
```
ID=23979 BP1=F:LG08:7379743 BP2=F:LG04:1049262 DISCORDANT=4 SCORE=0.571429
ID=23979 BP1=R:LG08:7379779 BP2=R:LG04:1049262 DISCORDANT=4 SCORE=0.800000
```
`BP2` have a same value in this record.

Should I skip this record if `BP2` have a same value in this record?

Regards!

**Comment by Mesh89** [comment]
Hi,

I pushed a fix for that. Can you try?

**Comment by Keliang-Lyu** [comment]
> Hi,
> 
> I pushed a fix for that. Can you try?

OK, thank you. I will try the new version.

**Comment by Keliang-Lyu** [comment]
> Hi,
> 
> I pushed a fix for that. Can you try?

Hi，Mesh89.
There is a new error, when I try  to run the new version.

```
Traceback (most recent call last):
  File "trans2ins.py", line 29, in <module>
    bp = tra_bkp_t(line)
  File "trans2ins.py", line 21, in __init__
    self.precision = sl[8]
IndexError: list index out of range
```

I notice that the code is used for parsing the `stdout` of `tran2sv.py`.  The `stdout` of `tran2sv.py` is only 8 values.
Should I replace `sl[8]` to `sl[7]`?

**Comment by Mesh89** [comment]
I updated trans2sv.py. It should work now.

**Comment by Keliang-Lyu** [comment]
> I updated trans2sv.py. It should work now.

Thank you for your help. 

I update the `trans2sv.py`.  There is a new error, when I try to run the new pipeline.
```
Traceback (most recent call last):
  File "trans2sv.py", line 11, in <module>
    sr = int(sl[4].split('=')[1])
ValueError: invalid literal for int() with base 10: '6.458333'
```

Here is the record of TranSurVeyor.
```
ID=0 BP1=R:LG02:3479720 BP2=R:LG04:22104523 DISCORDANT=155 SCORE=6.458333
ID=0 BP1=F:LG02:3479441 BP2=F:LG04:22104988 DISCORDANT=83 SCORE=2.677419
```
Regards!

**Comment by Mesh89** [comment]
Sorry about that. I uploaded a wrong version of the scripts.
Now I should have uploaded the files that we used for data production. I personally tried it and it worked for me.
Let me know if you encounter any more issues.

**Comment by Keliang-Lyu** [comment]
> Sorry about that. I uploaded a wrong version of the scripts. Now I should have uploaded the files that we used for data production. I personally tried it and it worked for me. Let me know if you encounter any more issues.

OK, Thank you for your help.
