### ISSUE TITLE
What does the 'DUP' tag mean?

### ISSUE THREAD

**Issue by Keliang-Lyu** [kensung-lab/IndelEnsembler#3]
Hi.
I finish the pipeline of IndelEnsembler. There is a record.
```
CLUSTER_28 LG01 14508 N LG01 14546 N DEL 1 1 2  CY005.MANTA_5,LG01:14508-14546
CLUSTER_60 LG01 41054 - LG01 41602 + DUP 1 1 3  CR011.SURVEYOR_57288,LG01:41054-41602
CLUSTER_63 LG01 41882 N LG01 41885 N INS 2 2 24  CR016.MANTA_8,LG01:41882-41885  CJ003.MANTA_10,LG01:41882-41885
```
There are three tags(DEL, DUP and INS) in the records.
DEL is deletion. INS is insertion.
What does the **DUP** tag mean in this record?

Regards!

**Comment by Mesh89** [comment]
Tandem duplication.

**Comment by Keliang-Lyu** [comment]
> Tandem duplication.

OK, thank you for your reply.
