### ISSUE TITLE
SurVIndel filter step problem

### ISSUE THREAD

**Issue by yuechaowu** [kensung-lab/IndelEnsembler#4]
Hi everyone. Recently I was using SurVIndel and IndelEnsembler, I'm stuck in the SurVIndel-filter step.
Here's the code  to run SurVIndel.
`python ~/data3/software/SurVIndel/surveyor.py ~/data4/project/large_indel/mutation/IndelEnsembler/bam/WGS_Lh3_unique_reDup_realigned_recal_fixmate.bam ~/data4/project/large_indel/mutation/IndelEnsembler/SurVIndel /home/wuyuechao/data4/reference/tigr7/tigr7_canonical.fa --threads 16`
The following files are generated above
-config.txt
-contig_map
-predictions.info
-random_pos.txt
-workspace

Then I ran the filer step and reported an error
`./filter /home/wuyuechao/data4/project/large_indel/mutation/IndelEnsembler/SurVIndel`

**_terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
[1]    32610 abort (core dumped)  ./filter_** 

please help, Thanks!

**Comment by Mesh89** [comment]
Hi,

SurVIndel's complete filter command is the following:

./filter /path/to/working/directory alpha-value score-cutoff min-size simple-repeats

Suggested values are 0.01 0.33 50, so the filter could look like this:

./filter /path/to/working/directory 0.01 0.33 50 /path/to/simple-repeats

Just using ./filter /path/to/working/directory is not correct.

Please see https://github.com/Mesh89/SurVIndel for more information.

**Comment by yuechaowu** [comment]
Got it, Thanks!
