### ISSUE TITLE
what does the number mean in the clustered files?

### ISSUE THREAD

**Issue by Github-Yilei** [kensung-lab/IndelEnsembler#5]
Hello,

I am calling structure variations with IndelEnsembler. But I couldn't understand the clustered files.

For example:
          CLUSTER_1229 chr1 266021 N chr1 266082 N DEL 28 44 2

  `28` is considered the number of samples. and what `44` and `2` mean in this situation. I wonder if there is a way to genotype or to transfer the result to a `Vcf` file to perform GWAS.

Thank you for your help and attention,
Yilei

**Comment by Mesh89** [comment]
44 is the number of different deletions. Sometimes two very similar deletions may be called in the same sample, and they are collapsed into one. As for 2, you can ignore it.

Unfortunately what we can provide, at the moment, is the list of samples of containing the deletion, but not whether the deletion is het or hom alt in the individual samples.

**Comment by Github-Yilei** [comment]
OK!  THANKS.   I'll close this issue.
